version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://postgres:Saisai22@database:5432/socialmedia"  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Nginx serves on port 80 inside container
    depends_on:
      - backend

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Saisai22
      POSTGRES_DB: socialmedia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  



volumes:
  pgdata:
