version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://postgres:Saisai22@database:5432/socialmedia"  

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Saisai22
      POSTGRES_DB: socialmedia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    image: vedjadhav/social_media-frontend
    container_name: social_media-frontend-1
    depends_on:
      - backend
    ports:
      - "3000:80"


volumes:
  pgdata:
