name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: vedjadhav/social_media-backend:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.workspace }}/frontend
        file: ${{ github.workspace }}/frontend/Dockerfile
        push: true
        tags: vedjadhav/social_media-frontend:latest
        build-args: |
          --no-cache
    - name: Verify Dockerfile existence
      run: |
        ls -l ./frontend
        cat ./frontend/Dockerfile
        